version: '3.1'

services:

  mongo:
    image: mongo:4.4-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: eve-route
    volumes:
      - ./.mongo:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports: ['27017:27017']

  mongo-express:
    image: mongo-express
    restart: always
    ports: ['8081:8081']
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
